config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#index'

  get 'about', to: 'about#index'
  get 'games', to: 'games#index'
  get 'teams', to: 'teams#index'
  get 'genres', to: 'genres#index'

  resources :games, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :reviews, only: [:index, :show]
  resources :teams, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :genres, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :teams
  has_many :reviews

  validates :title, :release_date, :rating, :summary, presence: true
  validates :title, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0,  less_than_or_equal_to: 5}

  def formatted_release_date
    release_date.strftime('%B %d, %Y') if release_date
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game
  validates :content, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :games
  validates :name, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @data_sources_info = "The dataset used for this project is a collection of video game information dating from 1980 to 2023. It provides data such as release dates, average ratings, developer teams, genres, and more. This dataset is sourced from Kaggle web site (https://www.kaggle.com/datasets/arnabchaki/popular-video-games-1980-2023).
                          The data can be devided into 4 tables. The Games table will have the following columns:id, title, release_date, rating, summary.
                          Teams table will have many to many relation with video games table and contain id and team name columns.
                          Genres table will also have many to many relation with video games table and have id and genre name columns.
                          Lastly, the Reviews table has 1 to many relation with video games table and should have id, game_id, and content as columns."

    @erd_description = "Below is the Entity-Relationship Diagram for this project. It represents the relationships between different tables in our database. It visualizes how data entities are connected and structured."

    @erd_image_path = 'erd.png'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(20)
  end

  def show
    @game = Game.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @games = Game.includes(:teams, :genres).where("title LIKE ?", wildcard_search)
    if params[:team].present? && params[:team][:team_ids].present?
      @games = @games.joins(:teams).where(teams: { id: params[:team][:team_ids] })
    end

    if params[:genre].present? && params[:genre][:genre_ids].present?
      @games = @games.joins(:genres).where(genres: { id: params[:genre][:genre_ids] })
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.page(params[:page]).per(20)
  end

  def show
    @genre = Genre.find(params[:id])
    @games = @genre.games
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @genres = Genre.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
    @game = @review.game
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.page(params[:page]).per(20)
  end

  def show
    @team = Team.find(params[:id])
    @games = @team.games
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @teams = Team.where("name LIKE ?", wildcard_search)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/about/index.html.erb
<h1 class="title is-1">About</h1>

<div class="mb-5">
    <h2 class="title is-2">Data Sources Information</h2>
    <p>
      <%= @data_sources_info %>
    </p>
  </div>

  <div class="mb-5">
    <h2 class="title is-2">Entity-Relationship Diagram (ERD)</h2>
    <p>
      <%= @erd_description %>
    </p>
    <%= image_tag(@erd_image_path, alt: 'ERD Diagram', class: 'img-fluid') %>
  </div>
</div>

app/views/common/_menu.html.erb
<nav class="navbar is-white">
<div class="navbar-menu">
    <div class="navbar-start">

      <a class="navbar-item">
        <%= link_to 'Home', home_path %>
      </a>

      <a class="navbar-item">
        <%= link_to 'About', about_path %>
      </a>

      <a class="navbar-item">
        <%= link_to 'Games', games_path %>
      </a>

      <a class="navbar-item">
        <%= link_to 'Teams', teams_path %>
      </a>

      <a class="navbar-item">
       <%= link_to 'Genres', genres_path %>
      </a>

      </div>
    </div>
</nav>

app/views/games/index.html.erb
<h1 class="title is-1">Games</h1>

<%= form_with(url: search_games_path, method: :get, local: true)  do %>
       <div class="field is-grouped mb-5">
        
        <div class="select">
            <%= collection_select(:team, :team_ids, Team.all, :id, :name, { prompt: "Select Team" }, class: "form-control") %>
        </div>

        <div class="select">
            <%= collection_select(:genre, :genre_ids, Genre.all, :id, :name, { prompt: "Select Genre" }, class: "form-control") %>
        </div>

        <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Games') %>
        </div>

        <div class="control">
          <%= submit_tag('Search', class: "button is-primary")%>
        </div>
       </div>
      <% end %>

<ul>
    <% @games.each do |g|%>
    <li>
        <%= link_to g.title, g %>
    </li>
     <% end %>
</ul>

<%= paginate @games %>

app/views/games/search.html.erb
<p class="mb-5">
  <% if @games %>
    Found <%= pluralize(@games.count, 'Games') %>.
  <% else %>
    No games were found.
  <% end %>

</p>
<ul>
  <% @games.each do |game| %>
    <li>
      <%= link_to game.title, game %>
    </li>
  <% end %>
</ul> 

app/views/games/show.html.erb
<% content_for(:html_title) {@game.title}%>
<div class = "content">
<h2 class="title is-2"><%= @game.title %></h2>
<progress class="progress is-info" value="<%=@game.rating%>" max=5>
    <%= @game.rating%>
</progress>
<p class="mb-5">
    <strong>
        This game received <%= @game.reviews.count %> reviews with avegare rating of <%= @game.rating %>. 
    </strong>
</p>
<p class="mb-5">
    <strong>
        The game was released on <%= @game.formatted_release_date %>. 
    </strong>
</p>

<p class="mb-5">
    <strong>
        Development team(s): 
    </strong>
    <ul>
        <% @game.teams.each do |team| %>
             <li>
               <%= link_to team.name, team_path(team) %>
            </li>
        <% end %>
    </ul>
</p>

<p class="mb-5">
    <strong>
        Genre(s): 
    </strong>
    <ul>
        <% @game.genres.each do |genre| %>
             <li>
               <%= link_to genre.name, genre_path(genre) %>
            </li>
        <% end %>
    </ul>
</p>

<p class="mb-5">
    <strong>
        Summary:
    </strong>
    <%= @game.summary %>
</p>
<p class="mb-5">
    <strong>
        Reviews:
    </strong>
    <ul>
        <% @game.reviews.each do |review| %>
             <li>
               <%= link_to review.content, review_path(review) %>
            </li>
        <% end %>
    </ul>
</p>
</div>

app/views/genres/index.html.erb
<h1 class="title is-1">All Genres</h1>

<%= form_with(url: search_genres_path, method: :get, local: true)  do |form|%>
       <div class="field is-grouped mb-5">
        <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Genres') %>
        </div>
        <div class="control">
          <%= submit_tag('Search', class: "button is-primary")%>
        </div>
       </div>
      <% end %>

<ul>
  <% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre_path(genre) %></li>
  <% end %>
</ul>

<%= paginate @genres %>

app/views/genres/search.html.erb
<p class="mb-5">
  <% if @genres %>
    Found <%= pluralize(@genres.count, 'Genres') %> when searching for: <%= params[:keywords] %>
  <% else %>
    No genres found when searching for: <%= params[:keywords] %>
  <% end %>
</p>
<ul>
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, genre %>
    </li>
  <% end %>
</ul> 

app/views/genres/show.html.erb
<h1 class="title is-1"><%= @genre.name %></h1>
<h2 class="title is-2">Below games are classified as <%= @genre.name %></h2>
<ul>
  <% @games.each do |game| %>
    <li><%= link_to game.title, game_path(game) %></li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1 class="title is-1">Welcome to Video Games Collection</h1>

<p>This is a collection of awesome video games.</p>

<ul>
    <li><%= link_to "Explore Games", games_path %></li>
    <li><%= link_to "Explore Development Teams", teams_path%></li>
    <li><%= link_to "Explore Game Genres", genres_path%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " - " if content_for?(:html_title)%>Popular Video Games 1980 - 2023</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <%= render 'common/menu' %>
    
    <section class = "section">
      <div class="container">
        <h1 class="title is-1">Popular Video Games 1980 - 2023</h1>
      </div>

      

    </section>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1 class="title is-1">Reviews</h1>

<ul>
  <% @reviews.each do |review| %>
    <li><%= link_to review.name, review_path(review) %></li>
  <% end %>
</ul>

app/views/reviews/show.html.erb
<h2 class= "title is-2">Review for <%= @game.title %> </h2>
<p class= "mb-5">
    <%= @review.content %>
</p>